/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CardId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BulkImportCard = IDL.Record({
  'id' : CardId,
  'recognitionConfidence' : IDL.Opt(IDL.Float64),
  'team' : IDL.Opt(IDL.Text),
  'year' : IDL.Nat16,
  'isRookieCard' : IDL.Bool,
  'serialNumber' : IDL.Opt(IDL.Text),
  'isAutographed' : IDL.Bool,
  'notes' : IDL.Opt(IDL.Text),
  'cardSeries' : IDL.Opt(IDL.Text),
  'playerName' : IDL.Text,
  'brand' : IDL.Text,
  'image' : ExternalBlob,
  'cardNumber' : IDL.Opt(IDL.Text),
});
export const BulkImportResult = IDL.Record({
  'created' : IDL.Nat,
  'errors' : IDL.Vec(IDL.Tuple(CardId, IDL.Text)),
  'updated' : IDL.Nat,
  'failed' : IDL.Nat,
});
export const CardFilters = IDL.Record({
  'team' : IDL.Opt(IDL.Text),
  'year' : IDL.Opt(IDL.Nat16),
  'isRookieCard' : IDL.Opt(IDL.Bool),
  'isAutographed' : IDL.Opt(IDL.Bool),
  'cardSeries' : IDL.Opt(IDL.Text),
  'playerName' : IDL.Opt(IDL.Text),
  'brand' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const PricePoint = IDL.Record({
  'timestamp' : Time,
  'price' : IDL.Opt(IDL.Float64),
});
export const CardMetadata = IDL.Record({
  'id' : CardId,
  'averagePrice' : IDL.Opt(IDL.Float64),
  'recognitionConfidence' : IDL.Opt(IDL.Float64),
  'team' : IDL.Text,
  'year' : IDL.Nat16,
  'priceHistory' : IDL.Vec(PricePoint),
  'isRookieCard' : IDL.Bool,
  'priceLastUpdated' : IDL.Opt(Time),
  'serialNumber' : IDL.Opt(IDL.Text),
  'isAutographed' : IDL.Bool,
  'notes' : IDL.Opt(IDL.Text),
  'cardSeries' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'playerName' : IDL.Text,
  'brand' : IDL.Text,
  'image' : ExternalBlob,
  'cardNumber' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PaginatedResult = IDL.Record({
  'total' : IDL.Nat,
  'hasMore' : IDL.Bool,
  'cards' : IDL.Vec(CardMetadata),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCard' : IDL.Func(
      [
        CardId,
        IDL.Nat16,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        ExternalBlob,
        IDL.Opt(IDL.Float64),
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkImportCards' : IDL.Func(
      [IDL.Vec(BulkImportCard)],
      [BulkImportResult],
      [],
    ),
  'deleteCard' : IDL.Func([CardId], [], []),
  'filterCards' : IDL.Func([CardFilters], [IDL.Vec(CardMetadata)], ['query']),
  'getAllCards' : IDL.Func([], [IDL.Vec(CardMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCardById' : IDL.Func([CardId], [CardMetadata], ['query']),
  'getPriceHistory' : IDL.Func([CardId], [IDL.Vec(PricePoint)], ['query']),
  'getRecentlyChangedCards' : IDL.Func([], [IDL.Vec(CardMetadata)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'refreshCardPrice' : IDL.Func([CardId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCards' : IDL.Func(
      [CardFilters, IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
      [PaginatedResult],
      ['query'],
    ),
  'transform' : IDL.Func([TransformationInput], [TransformationOutput], []),
  'updateCard' : IDL.Func(
      [
        CardId,
        IDL.Nat16,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        ExternalBlob,
        IDL.Opt(IDL.Float64),
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CardId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BulkImportCard = IDL.Record({
    'id' : CardId,
    'recognitionConfidence' : IDL.Opt(IDL.Float64),
    'team' : IDL.Opt(IDL.Text),
    'year' : IDL.Nat16,
    'isRookieCard' : IDL.Bool,
    'serialNumber' : IDL.Opt(IDL.Text),
    'isAutographed' : IDL.Bool,
    'notes' : IDL.Opt(IDL.Text),
    'cardSeries' : IDL.Opt(IDL.Text),
    'playerName' : IDL.Text,
    'brand' : IDL.Text,
    'image' : ExternalBlob,
    'cardNumber' : IDL.Opt(IDL.Text),
  });
  const BulkImportResult = IDL.Record({
    'created' : IDL.Nat,
    'errors' : IDL.Vec(IDL.Tuple(CardId, IDL.Text)),
    'updated' : IDL.Nat,
    'failed' : IDL.Nat,
  });
  const CardFilters = IDL.Record({
    'team' : IDL.Opt(IDL.Text),
    'year' : IDL.Opt(IDL.Nat16),
    'isRookieCard' : IDL.Opt(IDL.Bool),
    'isAutographed' : IDL.Opt(IDL.Bool),
    'cardSeries' : IDL.Opt(IDL.Text),
    'playerName' : IDL.Opt(IDL.Text),
    'brand' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const PricePoint = IDL.Record({
    'timestamp' : Time,
    'price' : IDL.Opt(IDL.Float64),
  });
  const CardMetadata = IDL.Record({
    'id' : CardId,
    'averagePrice' : IDL.Opt(IDL.Float64),
    'recognitionConfidence' : IDL.Opt(IDL.Float64),
    'team' : IDL.Text,
    'year' : IDL.Nat16,
    'priceHistory' : IDL.Vec(PricePoint),
    'isRookieCard' : IDL.Bool,
    'priceLastUpdated' : IDL.Opt(Time),
    'serialNumber' : IDL.Opt(IDL.Text),
    'isAutographed' : IDL.Bool,
    'notes' : IDL.Opt(IDL.Text),
    'cardSeries' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'playerName' : IDL.Text,
    'brand' : IDL.Text,
    'image' : ExternalBlob,
    'cardNumber' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PaginatedResult = IDL.Record({
    'total' : IDL.Nat,
    'hasMore' : IDL.Bool,
    'cards' : IDL.Vec(CardMetadata),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCard' : IDL.Func(
        [
          CardId,
          IDL.Nat16,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          ExternalBlob,
          IDL.Opt(IDL.Float64),
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkImportCards' : IDL.Func(
        [IDL.Vec(BulkImportCard)],
        [BulkImportResult],
        [],
      ),
    'deleteCard' : IDL.Func([CardId], [], []),
    'filterCards' : IDL.Func([CardFilters], [IDL.Vec(CardMetadata)], ['query']),
    'getAllCards' : IDL.Func([], [IDL.Vec(CardMetadata)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCardById' : IDL.Func([CardId], [CardMetadata], ['query']),
    'getPriceHistory' : IDL.Func([CardId], [IDL.Vec(PricePoint)], ['query']),
    'getRecentlyChangedCards' : IDL.Func(
        [],
        [IDL.Vec(CardMetadata)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'refreshCardPrice' : IDL.Func([CardId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCards' : IDL.Func(
        [CardFilters, IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
        [PaginatedResult],
        ['query'],
      ),
    'transform' : IDL.Func([TransformationInput], [TransformationOutput], []),
    'updateCard' : IDL.Func(
        [
          CardId,
          IDL.Nat16,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          ExternalBlob,
          IDL.Opt(IDL.Float64),
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };