/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BulkImportCard {
  'id' : CardId,
  'recognitionConfidence' : [] | [number],
  'team' : [] | [string],
  'year' : number,
  'isRookieCard' : boolean,
  'serialNumber' : [] | [string],
  'isAutographed' : boolean,
  'notes' : [] | [string],
  'cardSeries' : [] | [string],
  'playerName' : string,
  'brand' : string,
  'image' : ExternalBlob,
  'cardNumber' : [] | [string],
}
export interface BulkImportResult {
  'created' : bigint,
  'errors' : Array<[CardId, string]>,
  'updated' : bigint,
  'failed' : bigint,
}
export interface CardFilters {
  'team' : [] | [string],
  'year' : [] | [number],
  'isRookieCard' : [] | [boolean],
  'isAutographed' : [] | [boolean],
  'cardSeries' : [] | [string],
  'playerName' : [] | [string],
  'brand' : [] | [string],
}
export type CardId = string;
export interface CardMetadata {
  'id' : CardId,
  'averagePrice' : [] | [number],
  'recognitionConfidence' : [] | [number],
  'team' : string,
  'year' : number,
  'priceHistory' : Array<PricePoint>,
  'isRookieCard' : boolean,
  'priceLastUpdated' : [] | [Time],
  'serialNumber' : [] | [string],
  'isAutographed' : boolean,
  'notes' : [] | [string],
  'cardSeries' : [] | [string],
  'timestamp' : Time,
  'playerName' : string,
  'brand' : string,
  'image' : ExternalBlob,
  'cardNumber' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface PaginatedResult {
  'total' : bigint,
  'hasMore' : boolean,
  'cards' : Array<CardMetadata>,
}
export interface PricePoint { 'timestamp' : Time, 'price' : [] | [number] }
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCard' : ActorMethod<
    [
      CardId,
      number,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      ExternalBlob,
      [] | [number],
      boolean,
      boolean,
      string,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkImportCards' : ActorMethod<[Array<BulkImportCard>], BulkImportResult>,
  'deleteCard' : ActorMethod<[CardId], undefined>,
  'filterCards' : ActorMethod<[CardFilters], Array<CardMetadata>>,
  'getAllCards' : ActorMethod<[], Array<CardMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCardById' : ActorMethod<[CardId], CardMetadata>,
  'getPriceHistory' : ActorMethod<[CardId], Array<PricePoint>>,
  'getRecentlyChangedCards' : ActorMethod<[], Array<CardMetadata>>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'refreshCardPrice' : ActorMethod<[CardId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchCards' : ActorMethod<
    [CardFilters, [] | [string], bigint, bigint],
    PaginatedResult
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCard' : ActorMethod<
    [
      CardId,
      number,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      ExternalBlob,
      [] | [number],
      boolean,
      boolean,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];