/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CardMetadata {
    id: CardId;
    averagePrice?: number;
    recognitionConfidence?: number;
    team: string;
    year: number;
    priceHistory: Array<PricePoint>;
    isRookieCard: boolean;
    priceLastUpdated?: Time;
    serialNumber?: string;
    isAutographed: boolean;
    notes?: string;
    cardSeries?: string;
    timestamp: Time;
    playerName: string;
    brand: string;
    image: ExternalBlob;
    cardNumber?: string;
}
export interface BulkImportCard {
    id: CardId;
    recognitionConfidence?: number;
    team?: string;
    year: number;
    isRookieCard: boolean;
    serialNumber?: string;
    isAutographed: boolean;
    notes?: string;
    cardSeries?: string;
    playerName: string;
    brand: string;
    image: ExternalBlob;
    cardNumber?: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface BulkImportResult {
    created: bigint;
    errors: Array<[CardId, string]>;
    updated: bigint;
    failed: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PaginatedResult {
    total: bigint;
    hasMore: boolean;
    cards: Array<CardMetadata>;
}
export interface PricePoint {
    timestamp: Time;
    price?: number;
}
export interface CardFilters {
    team?: string;
    year?: number;
    isRookieCard?: boolean;
    isAutographed?: boolean;
    cardSeries?: string;
    playerName?: string;
    brand?: string;
}
export type CardId = string;
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCard(id: CardId, year: number, playerName: string, brand: string, serialNumber: string | null, cardNumber: string | null, cardSeries: string | null, notes: string | null, image: ExternalBlob, recognitionConfidence: number | null, isRookieCard: boolean, isAutographed: boolean, team: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkImportCards(cardsToImport: Array<BulkImportCard>): Promise<BulkImportResult>;
    deleteCard(id: CardId): Promise<void>;
    filterCards(filters: CardFilters): Promise<Array<CardMetadata>>;
    getAllCards(): Promise<Array<CardMetadata>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCardById(id: CardId): Promise<CardMetadata>;
    getPriceHistory(id: CardId): Promise<Array<PricePoint>>;
    getRecentlyChangedCards(): Promise<Array<CardMetadata>>;
    getUserProfile(user: string): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    refreshCardPrice(id: CardId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchCards(filters: CardFilters, searchTerm: string | null, pageSize: bigint, offset: bigint): Promise<PaginatedResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCard(id: CardId, year: number, playerName: string, brand: string, serialNumber: string | null, cardNumber: string | null, cardSeries: string | null, notes: string | null, image: ExternalBlob, recognitionConfidence: number | null, isRookieCard: boolean, isAutographed: boolean, team: string): Promise<void>;
}
import type { BulkImportCard as _BulkImportCard, CardFilters as _CardFilters, CardId as _CardId, CardMetadata as _CardMetadata, ExternalBlob as _ExternalBlob, PaginatedResult as _PaginatedResult, PricePoint as _PricePoint, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCard(arg0: CardId, arg1: number, arg2: string, arg3: string, arg4: string | null, arg5: string | null, arg6: string | null, arg7: string | null, arg8: ExternalBlob, arg9: number | null, arg10: boolean, arg11: boolean, arg12: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCard(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7), await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCard(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7), await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkImportCards(arg0: Array<BulkImportCard>): Promise<BulkImportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportCards(await to_candid_vec_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportCards(await to_candid_vec_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCard(arg0: CardId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCard(arg0);
            return result;
        }
    }
    async filterCards(arg0: CardFilters): Promise<Array<CardMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterCards(to_candid_CardFilters_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterCards(to_candid_CardFilters_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCards(): Promise<Array<CardMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCards();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCards();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCardById(arg0: CardId): Promise<CardMetadata> {
        if (this.processError) {
            try {
                const result = await this.actor.getCardById(arg0);
                return from_candid_CardMetadata_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCardById(arg0);
            return from_candid_CardMetadata_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriceHistory(arg0: CardId): Promise<Array<PricePoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriceHistory(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriceHistory(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentlyChangedCards(): Promise<Array<CardMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentlyChangedCards();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentlyChangedCards();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async refreshCardPrice(arg0: CardId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshCardPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshCardPrice(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchCards(arg0: CardFilters, arg1: string | null, arg2: bigint, arg3: bigint): Promise<PaginatedResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCards(to_candid_CardFilters_n16(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_PaginatedResult_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCards(to_candid_CardFilters_n16(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_PaginatedResult_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCard(arg0: CardId, arg1: number, arg2: string, arg3: string, arg4: string | null, arg5: string | null, arg6: string | null, arg7: string | null, arg8: ExternalBlob, arg9: number | null, arg10: boolean, arg11: boolean, arg12: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCard(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7), await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCard(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7), await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12);
            return result;
        }
    }
}
async function from_candid_CardMetadata_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CardMetadata): Promise<CardMetadata> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_PaginatedResult_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedResult): Promise<PaginatedResult> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PricePoint_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PricePoint): PricePoint {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CardId;
    averagePrice: [] | [number];
    recognitionConfidence: [] | [number];
    team: string;
    year: number;
    priceHistory: Array<_PricePoint>;
    isRookieCard: boolean;
    priceLastUpdated: [] | [_Time];
    serialNumber: [] | [string];
    isAutographed: boolean;
    notes: [] | [string];
    cardSeries: [] | [string];
    timestamp: _Time;
    playerName: string;
    brand: string;
    image: _ExternalBlob;
    cardNumber: [] | [string];
}): Promise<{
    id: CardId;
    averagePrice?: number;
    recognitionConfidence?: number;
    team: string;
    year: number;
    priceHistory: Array<PricePoint>;
    isRookieCard: boolean;
    priceLastUpdated?: Time;
    serialNumber?: string;
    isAutographed: boolean;
    notes?: string;
    cardSeries?: string;
    timestamp: Time;
    playerName: string;
    brand: string;
    image: ExternalBlob;
    cardNumber?: string;
}> {
    return {
        id: value.id,
        averagePrice: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.averagePrice)),
        recognitionConfidence: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.recognitionConfidence)),
        team: value.team,
        year: value.year,
        priceHistory: from_candid_vec_n22(_uploadFile, _downloadFile, value.priceHistory),
        isRookieCard: value.isRookieCard,
        priceLastUpdated: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.priceLastUpdated)),
        serialNumber: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.serialNumber)),
        isAutographed: value.isAutographed,
        notes: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.notes)),
        cardSeries: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.cardSeries)),
        timestamp: value.timestamp,
        playerName: value.playerName,
        brand: value.brand,
        image: await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value.image),
        cardNumber: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.cardNumber))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timestamp: _Time;
    price: [] | [number];
}): {
    timestamp: Time;
    price?: number;
} {
    return {
        timestamp: value.timestamp,
        price: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.price))
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    hasMore: boolean;
    cards: Array<_CardMetadata>;
}): Promise<{
    total: bigint;
    hasMore: boolean;
    cards: Array<CardMetadata>;
}> {
    return {
        total: value.total,
        hasMore: value.hasMore,
        cards: await from_candid_vec_n18(_uploadFile, _downloadFile, value.cards)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CardMetadata>): Promise<Array<CardMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CardMetadata_n19(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PricePoint>): Array<PricePoint> {
    return value.map((x)=>from_candid_PricePoint_n23(_uploadFile, _downloadFile, x));
}
async function to_candid_BulkImportCard_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BulkImportCard): Promise<_BulkImportCard> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_CardFilters_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardFilters): _CardFilters {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: CardId;
    recognitionConfidence?: number;
    team?: string;
    year: number;
    isRookieCard: boolean;
    serialNumber?: string;
    isAutographed: boolean;
    notes?: string;
    cardSeries?: string;
    playerName: string;
    brand: string;
    image: ExternalBlob;
    cardNumber?: string;
}): Promise<{
    id: _CardId;
    recognitionConfidence: [] | [number];
    team: [] | [string];
    year: number;
    isRookieCard: boolean;
    serialNumber: [] | [string];
    isAutographed: boolean;
    notes: [] | [string];
    cardSeries: [] | [string];
    playerName: string;
    brand: string;
    image: _ExternalBlob;
    cardNumber: [] | [string];
}> {
    return {
        id: value.id,
        recognitionConfidence: value.recognitionConfidence ? candid_some(value.recognitionConfidence) : candid_none(),
        team: value.team ? candid_some(value.team) : candid_none(),
        year: value.year,
        isRookieCard: value.isRookieCard,
        serialNumber: value.serialNumber ? candid_some(value.serialNumber) : candid_none(),
        isAutographed: value.isAutographed,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        cardSeries: value.cardSeries ? candid_some(value.cardSeries) : candid_none(),
        playerName: value.playerName,
        brand: value.brand,
        image: await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value.image),
        cardNumber: value.cardNumber ? candid_some(value.cardNumber) : candid_none()
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    team?: string;
    year?: number;
    isRookieCard?: boolean;
    isAutographed?: boolean;
    cardSeries?: string;
    playerName?: string;
    brand?: string;
}): {
    team: [] | [string];
    year: [] | [number];
    isRookieCard: [] | [boolean];
    isAutographed: [] | [boolean];
    cardSeries: [] | [string];
    playerName: [] | [string];
    brand: [] | [string];
} {
    return {
        team: value.team ? candid_some(value.team) : candid_none(),
        year: value.year ? candid_some(value.year) : candid_none(),
        isRookieCard: value.isRookieCard ? candid_some(value.isRookieCard) : candid_none(),
        isAutographed: value.isAutographed ? candid_some(value.isAutographed) : candid_none(),
        cardSeries: value.cardSeries ? candid_some(value.cardSeries) : candid_none(),
        playerName: value.playerName ? candid_some(value.playerName) : candid_none(),
        brand: value.brand ? candid_some(value.brand) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BulkImportCard>): Promise<Array<_BulkImportCard>> {
    return await Promise.all(value.map(async (x)=>await to_candid_BulkImportCard_n14(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
